#pragma once

#if INSTRUMENTATION_ENABLED
#define TAKEOVER_DEBUG true
#define OPTIMALPOSITIONS_DEBUG true
#define OPTIMALPOSITIONS_DEBUG_VERBOSE true
#define OPTIMALRETURN_DEBUG true
#define OPTIMALRETURN_DEBUG_VERBOSE true
#endif
