#pragma once

#if INSTRUMENTATION_ENABLED
#define TAKEOVER_DEBUG false
#define OPTIMALPOSITIONS_DEBUG false
#define OPTIMALRETURN_DEBUG false
#endif

#if INSTRUMENTATION_ENABLED_VERBOSE
#define OPTIMALPOSITIONS_DEBUG_VERBOSE false
#define OPTIMALRETURN_DEBUG_VERBOSE false
#endif
