#pragma once

#include "Common.h"
#include "Noncopyable.h"

#include "../MiningOptimizationConfiguration.h"
#include "../DataModel/PositionAndVelocity.h"
#include "../DataModel/Path.h"

#include <optional>

namespace MiningOptimization
{
    // Struct we use to store the tree generated by the solver
    template <typename ObservationType>
    struct SolverResult
    {
        // The positions expected to be visited along the path to the next branch
        // Starts with the position of the node that starts this branch
        std::deque<PositionAndVelocity> pathToNextBranch;

        // Same as the above, but references to the path nodes, for use in debugging and if we need to re-run the solver from a later point.
        std::deque<const PathNode<ObservationType>*> pathNodesToNextBranch;

        // The possible next branches once this branch has been traversed
        // The user can identify which next branch is being followed by checking its first position
        // If this is empty, then this branch is the last part of the path
        std::vector<SolverResult> nextBranches;

        // Frames where we intend to resend while on this branch
        std::set<int> resendFramesOnThisBranch;

        // The predicted arrival frame to the patch or depot
        std::map<int, double> arrivalFramesWithProbabilities;

        // The predicted "action frame" (transition to mining or delivery of resource)
        // For takeover this does not respect the actual takeover frame - it is simply the frame after arrival where the worker's order process
        // timer reaches zero (weighted by probability if the order process timer value is not precisely known)
        std::map<int, double> actionFramesWithProbabilities;

        // The predicted delays (not facing patch, collision); can be negative for returns with preserved speed
        std::map<int, double> delaysWithProbabilities;

        // The predicted patch switch frames with probabilities
        std::map<int, double> patchSwitchFramesWithProbabilities;

        // The predicted patch lock frames with probabilities
        // The probability here does not include the probability that patch locking is possible at the given frame, since this changes over time
        // as our predictions shift
        // If the solver does not think patch locking is possible, this will be empty
        std::map<int, double> patchLockFramesWithProbabilities;

#if USE_NEXT_PATH_LENGTHS
        // The expected next path lengths with probabilities
        // This is not expected to be very exact, but can be used to nudge the worker towards picking paths that get it onto a better next path.
        std::map<int, double> nextPathLengthWithProbabilities;
#endif

        // Gets the resend frames for all branches below this one if they are stable
        // If the resend frames are not stable, returns nullopt
        std::optional<std::set<int>> aggregatedResendFramesIfStable() const;

        // Formats the frame predictions as a string
        [[nodiscard]] std::string framePredictions() const;

        // Computes the average value of the map, weighting each value by its probability.
        // This method assumes the probabilities sum up to 1 (which is the case for the maps not related to patch locking)
        static double mapAverage(const std::map<int, double> &map);

        // Sums the probability values of the map. Only relevant for the maps related to patch locking, as the others always sum to 1.
        static double probabilitySum(const std::map<int, double> &map);

        // Ensure we never copy solver results, since they have a full tree structure
        [[no_unique_address]] noncopyable _ = {};
    };
}
