#pragma once

#include "Common.h"
#include "Noncopyable.h"

#include "../MiningOptimizationConfiguration.h"
#include "../DataModel/PositionAndVelocity.h"
#include "../DataModel/Path.h"

#include <optional>

namespace MiningOptimization
{
    // Simple struct to pack the arrival frame with the metadata we need for gather takeover
    struct SolverArrivalData
    {
        int arrivalFrame;
        int tenDistanceFrame;
        int resendAlwaysArrivesFrame;

        bool operator==(const SolverArrivalData &other) const
        {
            return std::tie(arrivalFrame, tenDistanceFrame, resendAlwaysArrivesFrame)
                == std::tie(other.arrivalFrame, other.tenDistanceFrame, other.resendAlwaysArrivesFrame);
        }

        bool operator<(const SolverArrivalData &other) const
        {
            return std::tie(arrivalFrame, tenDistanceFrame, resendAlwaysArrivesFrame)
                < std::tie(other.arrivalFrame, other.tenDistanceFrame, other.resendAlwaysArrivesFrame);
        }

        friend std::ostream& operator<< (std::ostream& os, const SolverArrivalData& data)
        {
            os << data.arrivalFrame;
            return os;
        }
    };

    // Struct we use to store the tree generated by the solver
    template <typename ObservationType>
    struct SolverResult
    {
        // The positions expected to be visited along the path to the next branch
        // Starts with the position of the node that starts this branch
        std::deque<PositionAndVelocity> pathToNextBranch;

        // The possible next branches once this branch has been traversed
        // The user can identify which next branch is being followed by checking its first position
        // If this is empty, then this branch is the last part of the path
        std::vector<SolverResult> nextBranches;

        // Frames where we intend to resend while on this branch
        std::set<int> resendFramesOnThisBranch;

        // The predicted arrival data to the patch or depot
        std::map<SolverArrivalData, double> arrivalDataWithProbabilities;

        // The predicted "action frame" (transition to mining or delivery of resource)
        // For takeover this does not respect the actual takeover frame - it is simply the frame after arrival where the worker's order process
        // timer reaches zero (weighted by probability if the order process timer value is not precisely known)
        std::map<int, double> actionFramesWithProbabilities;

        // The predicted delays (not facing patch, collision); can be negative for returns with preserved speed
        std::map<int, double> delaysWithProbabilities;

        // The set of takeover action frames that are guaranteed to be achievable
        // The last frame is the set is the first frame where all later frames are achievable (since the worker eventually will arrive at
        // the patch and be capable of resending at will)
        // Lazily-initialized when the optimizer asks for it, since we don't need this for gathers that aren't takeovers
        std::optional<std::set<int>> takeoverActionFrames;

#if USE_NEXT_PATH_LENGTHS
        // The expected next path lengths with probabilities
        // This is not expected to be very exact, but can be used to nudge the worker towards picking paths that get it onto a better next path.
        std::map<int, double> nextPathLengthWithProbabilities;
#endif

        // Gets the resend frames for all branches below this one if they are stable
        // If the resend frames are not stable, returns nullopt
        [[nodiscard]] std::optional<std::set<int>> aggregatedResendFramesIfStable() const;

        // Whether the arrival data contains a given frame
        [[nodiscard]] bool containsArrivalFrame(int arrivalFrame) const;

        // The latest arrival frame in the arrival data
        [[nodiscard]] int latestArrivalFrame() const;

        // Formats the frame predictions as a string
        [[nodiscard]] std::string framePredictions() const;

        // Computes the average value of the map, weighting each value by its probability.
        // This method assumes the probabilities sum up to 1 (which is the case for the maps not related to patch locking)
        static double mapAverage(const std::map<int, double> &map);

        // Sums the probability values of the map. Only relevant for the maps related to patch locking, as the others always sum to 1.
        static double probabilitySum(const std::map<int, double> &map);

        // Ensure we never copy solver results, since they have a full tree structure
        [[no_unique_address]] noncopyable _ = {};
    };
}
