#pragma once

#include "Resource.h"
#include "../DataModel/Path.h"

namespace MiningOptimization
{
    namespace {
        std::array<double, GATHER_FORECAST_FRAMES> emptyOtherPatchesForecast;
    }

    // Wrapper for the resend frames allowing us to also store some metadata
    struct SolverResends
    {
        // The frames on which to resend
        std::set<int> resendFrames;

        // Whether the final resend has been planned
        bool isFinal = false;
    };

    // Struct we use to store the tree generated by the solver
    struct SolverPathBranch
    {
        // The positions expected to be visited along the path to the next branch
        // Starts with the position of the node that starts this branch
        std::deque<PositionAndVelocity> pathToNextBranch;

        // The possible next branches once this branch has been traversed
        // The user can identify which next branch is being followed by checking its first position
        // If this is empty, then this branch is the last part of the path
        std::vector<SolverPathBranch> nextBranches;

        // Frames where we intend to resend while on this branch
        std::set<int> resendFramesOnThisBranch;

        // The predicted arrival frame to the patch or depot
        std::map<int, double> arrivalFramesWithProbabilities;

        // The predicted "action frame" (transition to mining or delivery of resource)
        // For cases where there is a predicted patch lock, this will either be the patch lock frame (if the patch lock happens after arrival)
        // or the mining start frame if the patch lock happened before
        std::map<int, double> actionFramesWithProbabilities;

        // The predicted delays (not facing patch, collision); can be negative for returns with preserved speed
        std::map<int, double> delaysWithProbabilities;

        // The predicted patch lock frames with probabilities
        // The probability here does not include the probability that patch locking is possible at the given frame, since this changes over time
        // as our predictions shift
        // If the solver does not think patch locking is possible, this will be empty
        std::map<int, double> patchLockFramesWithProbabilities;
    };

    template <typename ObservationType>
    class Solver
    {
    public:
        // Constructor used for single-worker gathering and return
        Solver(const PositionAndVelocity &startPosition,
               const std::vector<std::pair<PathNode<ObservationType>, uint8_t>> &nextPathNodes,
               int startFrame,
               int workerOrderProcessTimerAtStartFrame)
                : startPosition(startPosition)
                , initialNextPathNodes(nextPathNodes)
                , startFrame(startFrame)
                , workerOrderProcessTimerAtStartFrame(workerOrderProcessTimerAtStartFrame)
                , takeoverFrame(-1)
                , otherPatchesForecast(emptyOtherPatchesForecast)
        {}

        // Constructor used for double-worker gathering
        Solver(const PositionAndVelocity &startPosition,
               const std::vector<std::pair<PathNode<ObservationType>, uint8_t>> &nextPathNodes,
               int startFrame,
               int workerOrderProcessTimerAtStartFrame,
               int takeoverFrame,
               const std::array<double, GATHER_FORECAST_FRAMES> &otherPatchesForecast)
                : startPosition(startPosition)
                , initialNextPathNodes(nextPathNodes)
                , startFrame(startFrame)
                , workerOrderProcessTimerAtStartFrame(workerOrderProcessTimerAtStartFrame)
                , takeoverFrame(takeoverFrame)
                , otherPatchesForecast(otherPatchesForecast)
        {}

        SolverPathBranch execute();

    private:
        // The start position of this solver execution
        const PositionAndVelocity &startPosition;

        // The next path nodes and their weights from the start position
        const std::vector<std::pair<PathNode<ObservationType>, uint8_t>> &initialNextPathNodes;

        // The start frame of this solver execution
        int startFrame;

        // The worker's order process timer value at the start frame, or -1 if this is unknown
        int workerOrderProcessTimerAtStartFrame;

        // The frame when this worker is guaranteed to be able to take over from another worker, or -1 if this is a single-worker or return case
        int takeoverFrame;

        // The forecast of whether all other patches will be gathered in the frames after the start frame
        // Only relevant for two-worker gather, otherwise it will be set to a default value
        const std::array<double, GATHER_FORECAST_FRAMES> &otherPatchesForecast;

        struct ArrivalDetails
        {
            ObservationType arrivalData;
            int workerOrderProcessTimerAtArrival;
        };
        typedef std::vector<std::pair<ArrivalDetails, double>> NoResendArrivalDetails;

        NoResendArrivalDetails processNextNodes(const std::vector<std::pair<PathNode<ObservationType>, uint8_t>> &nextPathNodes,
                                                int frame,
                                                SolverResends &previousResends,
                                                int workerOrderProcessTimer);

        // Whether a resend is viable from the given node on the given frame with the given previous resend frames
        // A resend is viable if it can be issued and all possible resend nodes are either stable or have resend data available
        // The second return value is whether the resend must be the final resend, and is only relevant if the first value is true
        std::pair<bool, bool> isResendViableHere(const PathNode<ObservationType> &node,
                                                 int frame,
                                                 SolverResends &previousResends);

        /*
         * These methods are where the logic differs between gather and return paths. They are implemented in their own files for each
         * template specialization.
         */

        // Checks if a resend can be sent on the given frame
        bool canResendOnFrame(int frame, std::set<int> &previousResendFrames);
    };
}
